#***Digit Recognizer(MNIST) dataset using CNN***

In [2]:
import numpy as np
import pandas as  pd
import matplotlib.pyplot as plt
import zipfile

In [3]:
zip=zipfile.ZipFile('train.csv (2).zip')
zip.extractall()

In [4]:
df=pd.read_csv('train.csv')
df=df.dropna(how='any')
df

label  pixel0  pixel1  pixel2  ...  pixel780  pixel781  pixel782  pixel783
0          1       0       0       0  ...         0         0         0         0
1          0       0       0       0  ...         0         0         0         0
2          1       0       0       0  ...         0         0         0         0
3          4       0       0       0  ...         0         0         0         0
4          0       0       0       0  ...         0         0         0         0
...      ...     ...     ...     ...  ...       ...       ...       ...       ...
41995      0       0       0       0  ...         0         0         0         0
41996      1       0       0       0  ...         0         0         0         0
41997      7       0       0       0  ...         0         0         0         0
41998      6       0       0       0  ...         0         0         0         0
41999      9       0       0       0  ...         0         0         0         0

[42000 rows x 785 columns]

In [5]:
df['label'].unique()

array([1, 0, 4, 7, 3, 5, 8, 9, 2, 6])

In [6]:
y = df["label"]
X = df.drop(labels=["label"],axis=1)

In [7]:
X

pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0           0       0       0       0  ...         0         0         0         0
1           0       0       0       0  ...         0         0         0         0
2           0       0       0       0  ...         0         0         0         0
3           0       0       0       0  ...         0         0         0         0
4           0       0       0       0  ...         0         0         0         0
...       ...     ...     ...     ...  ...       ...       ...       ...       ...
41995       0       0       0       0  ...         0         0         0         0
41996       0       0       0       0  ...         0         0         0         0
41997       0       0       0       0  ...         0         0         0         0
41998       0       0       0       0  ...         0         0         0         0
41999       0       0       0       0  ...         0         0         0         0

[42000 rows x 784 columns]

In [8]:
y

0        1
1        0
2        1
3        4
4        0
        ..
41995    0
41996    1
41997    7
41998    6
41999    9
Name: label, Length: 42000, dtype: int64

In [9]:
X = X / 255.0

In [10]:
X

pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0         0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
1         0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
2         0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
3         0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
4         0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
...       ...     ...     ...     ...  ...       ...       ...       ...       ...
41995     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
41996     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
41997     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
41998     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0
41999     0.0     0.0     0.0     0.0  ...       0.0       0.0       0.0       0.0

[42000 rows x 784 columns]

In [11]:
X = X.values.reshape(-1,28,28,1)

In [12]:
X

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [13]:
from tensorflow.keras.utils import to_categorical 
y = to_categorical(y, 10)

In [14]:
y

array([[0., 1., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_val, Y_train, Y_val = train_test_split(X, y, test_size = 0.25, random_state=42)

In [16]:
print("x_train shape",X_train.shape)
print("x_val shape",X_val.shape)
print("y_train shape",Y_train.shape)
print("y_val shape",Y_val.shape)

x_train shape (31500, 28, 28, 1)
x_val shape (10500, 28, 28, 1)
y_train shape (31500, 10)
y_val shape (10500, 10)


In [29]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import BatchNormalization
from tensorflow.keras.layers import Dropout
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.optimizers import SGD

In [48]:
model = Sequential()
model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer='he_uniform', input_shape=(28, 28, 1)))
model.add(BatchNormalization())
model.add(MaxPooling2D((2, 2)))
model.add(Flatten())
model.add(Dense(100, activation='relu', kernel_initializer='he_uniform'))
model.add(BatchNormalization())
model.add(Dense(10, activation='softmax'))
opt = SGD(lr=0.01, momentum=0.9)

In [49]:
model.compile(optimizer=opt,loss='categorical_crossentropy',metrics=['accuracy'])

In [50]:
datagen = ImageDataGenerator(
        featurewise_center=False,  
        samplewise_center=False, 
        featurewise_std_normalization=False,  
        samplewise_std_normalization=False,  
        zca_whitening=False, 
        rotation_range=5,  
        zoom_range = 0.1, 
        width_shift_range=0.1,  
        height_shift_range=0.1,  
        horizontal_flip=False,  
        vertical_flip=False)  

datagen.fit(X_train)

In [43]:
model.fit(datagen.flow(X_train,Y_train, batch_size=20), validation_data = (X_val,Y_val),epochs = 1, steps_per_epoch=X_train.shape[0] )
model.save('DR.h5')

31500/31500 [==============================] - 38s 1ms/step - loss: 0.1891 - accuracy: 0.9412 - val_loss: 0.0899 - val_accuracy: 0.9728


In [46]:
print("Accuracy of the model is --> " , model.evaluate(X_val, Y_val, batch_size=20)[1]*100 , "%")
print("Loss of the model is --> " , model.evaluate(X_val, Y_val, batch_size=20)[0])

525/525 [==============================] - 3s 6ms/step - loss: 0.0899 - accuracy: 0.9728
Accuracy of the model is -->  97.27619290351868 %
525/525 [==============================] - 4s 7ms/step - loss: 0.0899 - accuracy: 0.9728
Loss of the model is -->  0.08989419043064117


#***Testing the model***

In [51]:
zip=zipfile.ZipFile('test.csv.zip')
zip.extractall()

In [63]:
from tensorflow.keras.models import load_model
model=load_model('DR.h5')
print("loaded model from disk")

loaded model from disk


In [68]:
test=pd.read_csv('test.csv')
test=test.dropna(how='any')
test

pixel0  pixel1  pixel2  pixel3  ...  pixel780  pixel781  pixel782  pixel783
0           0       0       0       0  ...         0         0         0         0
1           0       0       0       0  ...         0         0         0         0
2           0       0       0       0  ...         0         0         0         0
3           0       0       0       0  ...         0         0         0         0
4           0       0       0       0  ...         0         0         0         0
...       ...     ...     ...     ...  ...       ...       ...       ...       ...
27995       0       0       0       0  ...         0         0         0         0
27996       0       0       0       0  ...         0         0         0         0
27997       0       0       0       0  ...         0         0         0         0
27998       0       0       0       0  ...         0         0         0         0
27999       0       0       0       0  ...         0         0         0         0

[28000 rows x 784 columns]

In [69]:
X_test = test / 255.0

In [70]:
X_test = X_test.values.reshape(-1,28,28,1)

In [71]:
X_test

array([[[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]]],


       [[[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         ...,
         [0.],
         [0.],
         [0.]],

        ...,

        [[0.],
 

In [72]:
labels = model.predict(X_test)

In [73]:
labels = np.argmax(labels, axis=1)

In [74]:
len(labels)

28000

In [75]:
ss = pd.read_csv("sample_submission.csv")
ss.head()

ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [76]:
index = test.index.values + 1
data = {'ImageId' : index, "Label" : labels}
df = pd.DataFrame(data=data)
df.head()

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      0
4        5      3

In [77]:
df.to_csv('submission.csv', index=False)

In [78]:
df

ImageId  Label
0            1      2
1            2      0
2            3      9
3            4      0
4            5      3
...        ...    ...
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

[28000 rows x 2 columns]

In [79]:
final = pd.DataFrame({'ImageId' : index, "Label" : labels.astype(int).ravel()})
final.to_csv("final_submission.csv",index = False)